### ISSUE TITLE
Should this action include checkout?

### ISSUE THREAD

**Issue by stevector** [pantheon-systems/push-to-pantheon#16]
In working on https://github.com/stevector/push-to-pantheon/pull/2, @jazzsequence and I are questioning whether this action should include the `checkout` step at all or if we should implicitly require that all implementers of this action call `checkout` prior?

I built it this way so that the simplest consumption of this action could be very terse

```
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Push to Pantheon
      uses: stevector/push-to-pantheon@0.3
      with:
        ssh_key: ${{ secrets.PANTHEON_SSH_KEY }}
        machine_token: ${{ secrets.TERMINUS_MACHINE_TOKEN }}
        site: ${{ vars.PANTHEON_SITE }}
```

However, this then requires a lot of explaining and an additional param to account for teams doing `composer install` or `npm build` prior to calling `push-to-pantheon`. (What's currently in https://github.com/stevector/push-to-pantheon/pull/2)
